set -e
true
true
/usr/libexec/spades/spades-hammer /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/corrected/configs/config.info
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/compress_all.py --input_file /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/corrected/corrected.yaml --ext_python_modules_home /usr/share/spades --max_threads 16 --output_dir /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/corrected --gzip_output
true
true
/usr/libexec/spades/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K21/configs/config.info
/usr/libexec/spades/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K33/configs/config.info
/usr/libexec/spades/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K55/configs/config.info
/usr/libexec/spades/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/configs/config.info
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/copy_files.py /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/before_rr.fasta /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/before_rr.fasta /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/assembly_graph_after_simplification.gfa /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/assembly_graph_after_simplification.gfa /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/final_contigs.fasta /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/contigs.fasta /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/first_pe_contigs.fasta /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/first_pe_contigs.fasta /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/strain_graph.gfa /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/strain_graph.gfa /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/scaffolds.fasta /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/scaffolds.fasta /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/scaffolds.paths /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/scaffolds.paths /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/assembly_graph_with_scaffolds.gfa /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/assembly_graph_with_scaffolds.gfa /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/assembly_graph.fastg /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/assembly_graph.fastg /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/K77/final_contigs.paths /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/contigs.paths
true
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/scaffolds.fasta --misc_dir /mnt/c/Users/avinz/OneDrive/Desktop/finalprojectwholegenome/spadesout/misc --threshold_for_breaking_scaffolds 3
true
